### PR TITLE
run go mod tidy

### PR DESCRIPTION
**Pull request by hajimehoshi**

### CODE REVIEW

**Comment by gen2brain** [comment]
Huh, I think I don't like this, I will just rename examples to _examples, seems that should stop go mod from parsing that directory.

**Comment by hajimehoshi** [comment]
In this case we cannot run examples...

**Comment by gen2brain** [comment]
But any example can just be tried/used with `go mod init example` right, it just needs some extra commands.

**Comment by hajimehoshi** [comment]
I think users would expect they can run examples without additional commands.

**Comment by hajimehoshi** [comment]
Another suggestion is to separate repositories for the examples

**Comment by gen2brain** [comment]
Ok, for now, it is just renamed with an underscore and it is not user-friendly, I will see later to move examples to their own repo.

**Pull request closed without merging**
